package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Disease;

import java.util.List;
import org.mybatis.cdi.Mapper;

@Mapper
public interface DiseaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISEASE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISEASE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    int insert(Disease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISEASE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    Disease selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISEASE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    List<Disease> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISEASE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    int updateByPrimaryKey(Disease record);
}