package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Medicine;

import java.util.List;
import org.mybatis.cdi.Mapper;

@Mapper
public interface MedicineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEDICINE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEDICINE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    int insert(Medicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEDICINE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    Medicine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEDICINE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    List<Medicine> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEDICINE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    int updateByPrimaryKey(Medicine record);
}