package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Yearlycase;

import java.util.List;
import org.mybatis.cdi.Mapper;

@Mapper
public interface YearlycaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.YEARLYCASE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.YEARLYCASE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    int insert(Yearlycase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.YEARLYCASE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    Yearlycase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.YEARLYCASE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    List<Yearlycase> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.YEARLYCASE
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    int updateByPrimaryKey(Yearlycase record);
}