package lt.vu.mybatis.model;

public class Medicine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEDICINE.ID
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEDICINE.DESCRIPTION
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEDICINE.NAME
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEDICINE.ID
     *
     * @return the value of PUBLIC.MEDICINE.ID
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEDICINE.ID
     *
     * @param id the value for PUBLIC.MEDICINE.ID
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEDICINE.DESCRIPTION
     *
     * @return the value of PUBLIC.MEDICINE.DESCRIPTION
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEDICINE.DESCRIPTION
     *
     * @param description the value for PUBLIC.MEDICINE.DESCRIPTION
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEDICINE.NAME
     *
     * @return the value of PUBLIC.MEDICINE.NAME
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEDICINE.NAME
     *
     * @param name the value for PUBLIC.MEDICINE.NAME
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}