package lt.vu.mybatis.model;

public class Yearlycase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.YEARLYCASE.ID
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.YEARLYCASE.CASES
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    private Integer cases;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.YEARLYCASE.YEAR
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.YEARLYCASE.DISEASE_ID
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    private Integer diseaseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.YEARLYCASE.ID
     *
     * @return the value of PUBLIC.YEARLYCASE.ID
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.YEARLYCASE.ID
     *
     * @param id the value for PUBLIC.YEARLYCASE.ID
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.YEARLYCASE.CASES
     *
     * @return the value of PUBLIC.YEARLYCASE.CASES
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    public Integer getCases() {
        return cases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.YEARLYCASE.CASES
     *
     * @param cases the value for PUBLIC.YEARLYCASE.CASES
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    public void setCases(Integer cases) {
        this.cases = cases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.YEARLYCASE.YEAR
     *
     * @return the value of PUBLIC.YEARLYCASE.YEAR
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.YEARLYCASE.YEAR
     *
     * @param year the value for PUBLIC.YEARLYCASE.YEAR
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.YEARLYCASE.DISEASE_ID
     *
     * @return the value of PUBLIC.YEARLYCASE.DISEASE_ID
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    public Integer getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.YEARLYCASE.DISEASE_ID
     *
     * @param diseaseId the value for PUBLIC.YEARLYCASE.DISEASE_ID
     *
     * @mbg.generated Wed Apr 28 15:54:26 EEST 2021
     */
    public void setDiseaseId(Integer diseaseId) {
        this.diseaseId = diseaseId;
    }
}